### ISSUE TITLE
Too many ducks in Barbarian Village

### ISSUE THREAD

**Issue by verafeiyd** [skeldoor/duck-duck-goose#2]
Unfortunately theres literally 10 ducks for me on the first use of this plugin in barb village, far too many especially when using npc overhead text. Love the plugin though and would love to see many many more ducks around the game and other versions of this plugin for spiders and frogs
![image](https://github.com/skeldoor/duck-duck-goose/assets/123139321/2d8636af-bfcd-49f2-a64a-295ab3ac6107)

**Comment by verafeiyd** [comment]
Make that nearly 20 ducks, all in pretty much a 4x5 area, and there were still 5-8 stacked on top of each other here

![image](https://github.com/skeldoor/duck-duck-goose/assets/123139321/72260c56-13d4-4c7d-bc93-1b5b98ab8aff)

**Comment by verafeiyd** [comment]
I have realized if you afk in one spot and constantly disconnect in the same session, it will slowly adds to the bunch each time you log leading to a full army of ducks coming for your fish
![image](https://github.com/skeldoor/duck-duck-goose/assets/123139321/701bec45-f6cb-4611-a48d-b1e146e9d9af)
Nasty little devils

**Comment by skeldoor** [comment]
I’ve pushed a fix for this in build 1.0.1. Currently awaiting approval from the RL team. The trick was to get every other duck neutered to help cut down overpopulation

**Comment by verafeiyd** [comment]
very well done, this fixed the issue! would love to see this plugin expanded to most ponds and pieces of lake that dont have them yet, as this is one of the best ways to sort of "liven" up these empty water channels. 

(obviously none in morytania/the wildy but hey, this looks fantastic, and i want more :P)
